# Generated by Django 3.1.8 on 2021-10-23 17:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdmins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('telegram_id', models.CharField(max_length=255, verbose_name='ID в телеграмме')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Юзернейм в телеграмме')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Админ бота',
                'verbose_name_plural': 'Админы бота',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('telegram_id', models.CharField(max_length=255, verbose_name='ID в телеграмме')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Юзернейм в телеграмме')),
                ('referer', models.CharField(blank=True, max_length=30, verbose_name='Приведен пользователем')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('deposit', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Баланс')),
                ('last_update_deposit_date', models.DateField(default=django.utils.timezone.now, verbose_name='Последняя дата пополнения депозита')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('telegram_id', models.CharField(max_length=255, verbose_name='ID в телеграмме')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Юзернейм в телеграмме')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Сумма')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
            ],
            options={
                'verbose_name': 'Пополнение',
                'verbose_name_plural': 'Пополнения',
            },
        ),
        migrations.CreateModel(
            name='ReferralAccruals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Сумма')),
                ('accrual_to', models.CharField(max_length=255, verbose_name='Кому начислено')),
                ('accrual_from', models.CharField(max_length=255, verbose_name='За кого начислено')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Реферальное начисление',
                'verbose_name_plural': 'Реферальные начисления',
            },
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('telegram_id', models.CharField(max_length=255, verbose_name='ID в телеграмме')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Юзернейм в телеграмме')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Сумма')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
            ],
            options={
                'verbose_name': 'Вывод',
                'verbose_name_plural': 'Выводы',
            },
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('telegram_id', models.CharField(max_length=255, verbose_name='ID в телеграмме')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Юзернейм в телеграмме')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminbot.clients', verbose_name='Реферер')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
            },
        ),
    ]
