# Generated by Django 3.1.8 on 2021-10-24 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='card_number',
            field=models.CharField(max_length=20, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
    ]
