# Generated by Django 3.1.8 on 2021-10-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0002_auto_20211020_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='account',
            new_name='deposit',
        ),
        migrations.AddField(
            model_name='botadmins',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юзернейм в телеграмме'),
        ),
        migrations.AddField(
            model_name='clients',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юзернейм в телеграмме'),
        ),
    ]
