# Generated by Django 3.1.8 on 2021-10-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0002_auto_20211024_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='card_number',
            field=models.CharField(max_length=20, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='card_number',
            field=models.CharField(max_length=20, verbose_name='Номер карты'),
        ),
    ]
