# Generated by Django 3.1.8 on 2021-10-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0003_auto_20211021_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='last_update_deposit_date',
            field=models.DateField(auto_now=True, verbose_name='Последняя дата пополнения депозита'),
        ),
    ]
