# Generated by Django 3.1.8 on 2021-10-26 17:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0004_auto_20211024_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAccruals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('client', models.CharField(max_length=255, verbose_name='ID клиента в телеграмме')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Сумма')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Месячное начисление',
                'verbose_name_plural': 'Месячные начисления',
            },
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_update_deposit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 20, 17, 29, 234647), verbose_name='Последняя дата пополнения депозита'),
        ),
    ]
