# Generated by Django 3.1.8 on 2021-10-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0005_auto_20211023_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='deposit',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
    ]
