# Generated by Django 3.1.8 on 2021-10-28 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0006_auto_20211027_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='last_update_deposit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 14, 26, 4, 940390), verbose_name='Последняя дата пополнения депозита'),
        ),
        migrations.DeleteModel(
            name='Referrals',
        ),
    ]
