# Generated by Django 3.1.8 on 2021-10-23 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0006_auto_20211023_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='card_number',
            field=models.CharField(default='asd', max_length=16, verbose_name='Номер карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='first_name',
            field=models.CharField(default='asd', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='last_name',
            field=models.CharField(default='asd', max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='middle_name',
            field=models.CharField(default='asd', max_length=255, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='deposit',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Баланс'),
        ),
    ]
