# Generated by Django 3.1.8 on 2021-10-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0007_auto_20211023_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='refered_by',
            field=models.CharField(blank=True, max_length=30, verbose_name='Приведен пользователем'),
        ),
    ]
