# Generated by Django 3.1.8 on 2021-10-28 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0007_auto_20211028_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('card_number', models.CharField(max_length=255, verbose_name='Номер карты')),
            ],
            options={
                'verbose_name': 'Реквизит карты',
                'verbose_name_plural': 'Реквизиты карт',
            },
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_update_deposit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 17, 57, 30, 193889), verbose_name='Последняя дата пополнения депозита'),
        ),
    ]
