# Generated by Django 3.1.8 on 2021-10-28 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0008_auto_20211028_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='card_name',
            field=models.CharField(default='asd', max_length=255, verbose_name='Название карты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_update_deposit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 17, 58, 26, 5119), verbose_name='Последняя дата пополнения депозита'),
        ),
    ]
