# Generated by Django 3.1.8 on 2021-10-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0008_clients_refered_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='refered_by',
            new_name='referer',
        ),
    ]
