# Generated by Django 3.1.8 on 2021-10-28 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0009_auto_20211028_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст бота',
                'verbose_name_plural': 'Тексты бота',
            },
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_update_deposit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 18, 6, 28, 184188), verbose_name='Последняя дата пополнения депозита'),
        ),
    ]
